-- MySQL Script generated by MySQL Workbench
-- Tue Sep 28 18:46:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nova_poshta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nova_poshta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nova_poshta` DEFAULT CHARACTER SET utf8 ;
USE `nova_poshta` ;

-- -----------------------------------------------------
-- Table `nova_poshta`.`post_office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nova_poshta`.`post_office` ;

CREATE TABLE IF NOT EXISTS `nova_poshta`.`post_office` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `sity` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nova_poshta`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nova_poshta`.`client` ;

CREATE TABLE IF NOT EXISTS `nova_poshta`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_number_standart` VARCHAR(20) NOT NULL,
  `phone_number_formal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nova_poshta`.`parcel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nova_poshta`.`parcel` ;

CREATE TABLE IF NOT EXISTS `nova_poshta`.`parcel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_office_from_id` INT NOT NULL,
  `post_office_to_id` INT NOT NULL,
  `sender_id` INT NOT NULL,
  `reciver_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `weight` FLOAT NOT NULL,
  `dateSend` DATETIME(2) NOT NULL,
  `dateRecive` DATETIME(2) NOT NULL,
  `address_sender` VARCHAR(45) NOT NULL,
  `address_reciver` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPostOfficeFrom_idx` (`post_office_from_id` ASC) VISIBLE,
  INDEX `idPostOfficeTo_idx` (`post_office_to_id` ASC) VISIBLE,
  INDEX `idClient_idx` (`reciver_id` ASC) VISIBLE,
  INDEX `sender_id_idx` (`sender_id` ASC) VISIBLE,
  CONSTRAINT `post_office_from_id`
    FOREIGN KEY (`post_office_from_id`)
    REFERENCES `nova_poshta`.`post_office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_office_to_id`
    FOREIGN KEY (`post_office_to_id`)
    REFERENCES `nova_poshta`.`post_office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reciver_id`
    FOREIGN KEY (`reciver_id`)
    REFERENCES `nova_poshta`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sender_id`
    FOREIGN KEY (`sender_id`)
    REFERENCES `nova_poshta`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nova_poshta`.`worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nova_poshta`.`worker` ;

CREATE TABLE IF NOT EXISTS `nova_poshta`.`worker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_office_id` INT NOT NULL,
  `fist_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `patronymic` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  `passport_number` INT NOT NULL,
  `hirring_date` DATE NOT NULL,
  `working_hours` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPostOffice_idx` (`post_office_id` ASC) VISIBLE,
  UNIQUE INDEX `passport_number_UNIQUE` (`passport_number` ASC) VISIBLE,
  CONSTRAINT `post_office_id`
    FOREIGN KEY (`post_office_id`)
    REFERENCES `nova_poshta`.`post_office` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nova_poshta`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nova_poshta`.`delivery` ;

CREATE TABLE IF NOT EXISTS `nova_poshta`.`delivery` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parcel_id` INT NOT NULL,
  `worker_id` INT NOT NULL,
  `price` FLOAT NOT NULL,
  `type` ENUM('CAR', 'TRACK', 'COURIER') NOT NULL,
  `max_weight` FLOAT NOT NULL,
  `min_weight` FLOAT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `parcel_id_idx` (`parcel_id` ASC) VISIBLE,
  INDEX `worker_id_idx` (`worker_id` ASC) VISIBLE,
  CONSTRAINT `parcel_id`
    FOREIGN KEY (`parcel_id`)
    REFERENCES `nova_poshta`.`parcel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `worker_id`
    FOREIGN KEY (`worker_id`)
    REFERENCES `nova_poshta`.`worker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
